---
abstract: 'Builds and installs the V8 JavaScript engine'
author: []
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3624'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-V8
provides:
  Alien::V8:
    file: lib/Alien/V8.pm
    version: 0.03
requires:
  Archive::Tar: 1.38
  File::ShareDir: 1.00
  IPC::Cmd: 0.42
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
